src/Xtreem/AddressBookBundle/Entity/AddressBook.php
<?php

namespace Xtreem\AddressBookBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContext;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * AddressBook Entity.
 *
 * @ORM\Entity
 * @ORM\Table(name="address_book")
 * @Gedmo\SoftDeleteable(fieldName="deleted")
 */
class AddressBook
{
    /**
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string $firstName
     *
     * @ORM\Column(type="string", length=100, name="first_name", nullable=false)
     * @Assert\Length(max = "100", maxMessage="Please enter a first name that contains less than 100 characters.")
     * @Assert\NotBlank(message="Please enter a valid first name.")
     * @Assert\Type(type="string")
     */
    protected $firstName;

    /**
     * @var string $lastName
     *
     * @ORM\Column(type="string", length=100, name="last_name", nullable=false)
     * @Assert\Length(max = "100", maxMessage="Please enter a last name that contains less than 100 characters.")
     * @Assert\NotBlank(message="Please enter a valid last name.")
     * @Assert\Type(type="string")
     */
    protected $lastName;

    /**
     * @var string $line1
     *
     * @ORM\Column(type="string", length=32, name="line_1", nullable=false)
     * @Assert\Length(max = "32", maxMessage="The first line of your address should contain less than 32 characters.")
     * @Assert\NotBlank(message="Please provide a valid first address line.")
     * @Assert\Type(type="string")
     */
    protected $line1;

    /**
     * @var string $line2
     *
     * @ORM\Column(type="string", length=32, name="line_2", nullable=true)
     * @Assert\Length(
     *     max = "32",
     *     maxMessage="The second line of your address should contain less than 32 characters."
     * )
     * @Assert\Type(type="string")
     */
    protected $line2;

    /**
     * @var string $city
     *
     * @ORM\Column(type="string", length=32, name="city", nullable=false)
     * @Assert\Length(max = "32", maxMessage="Please enter a city that contains less than 32 characters.")
     * @Assert\NotBlank(message="Please provide a valid city.")
     * @Assert\Type(type="string")
     */
    protected $city;

    /**
     * @var string $postCode
     *
     * @ORM\Column(type="string", length=32, name="post_code", nullable=false)
     * @Assert\Length(max = "32", maxMessage="Please enter a postcode that contains less than 32 characters.")
     * @Assert\NotBlank(message="Please provide a valid postcode.")
     * @Assert\Type(type="string")
     */
    protected $postCode;

    /**
     * @var string $telephoneHome
     *
     * @ORM\Column(type="string", length=32, name="telephone_home", nullable=true)
     * @Assert\Length(
     *     max = "32",
     *     maxMessage="Please enter a home telephone number that contains less than 32 characters."
     * )
     * @Assert\Regex(
     *     pattern="/\d/",
     *     message="Your home telephone number should contain numbers only"
     * )
     * @Assert\Type(type="string")
     */
    protected $telephoneHome;

    /**
     * @var string $telephoneMobile
     *
     * @ORM\Column(type="string", length=32, name="telephone_mobile", nullable=true)
     * @Assert\Length(
     *     max = "32",
     *     maxMessage="Please enter a mobile telephone number that contains less than 32 characters."
     * )
     * @Assert\Regex(
     *     pattern="/\d/",
     *     message="Your mobile telephone number should contain numbers only"
     * )
     * @Assert\Type(type="string")
     */
    protected $telephoneMobile;

    /**
     * @var \DateTime $created
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", options={"format": "Y-m-d"})
     */
    protected $created;

    /**
     * @var \DateTime $updated
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @var \DateTime $deleted
     *
     * @ORM\Column(name="deleted", type="datetime", nullable=true)
     */
    protected $deleted;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set first name.
     *
     * @param string $firstName
     *
     * @return AddressBook
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get first name.
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set last name.
     *
     * @param string $lastName
     *
     * @return AddressBook
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get last name.
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Get first and last name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->firstName.' '.$this->lastName;
    }

    /**
     * Set line 1.
     *
     * @param string $line1
     *
     * @return AddressBook
     */
    public function setLine1($line1)
    {
        $this->line1 = $line1;

        return $this;
    }

    /**
     * Get line 1.
     *
     * @return string
     */
    public function getLine1()
    {
        return $this->line1;
    }

    /**
     * Set line 2.
     *
     * @param string $line2
     *
     * @return AddressBook
     */
    public function setLine2($line2)
    {
        $this->line2 = $line2;

        return $this;
    }

    /**
     * Get line 2.
     *
     * @return string
     */
    public function getLine2()
    {
        return $this->line2;
    }

    /**
     * Set city.
     *
     * @param string $city
     *
     * @return AddressBook
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city.
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set post code.
     *
     * @param string $postCode
     *
     * @return AddressBook
     */
    public function setPostCode($postCode)
    {
        $this->postCode = $postCode;

        return $this;
    }

    /**
     * Get post code.
     *
     * @return string
     */
    public function getPostCode()
    {
        return $this->postCode;
    }

    /**
     * Set home telephone number.
     *
     * @param string $telephoneHome
     *
     * @return AddressBook
     */
    public function setTelephoneHome($telephoneHome)
    {
        $this->telephoneHome = $telephoneHome;

        return $this;
    }

    /**
     * Get home telephone number.
     *
     * @return string
     */
    public function getTelephoneHome()
    {
        return $this->telephoneHome;
    }

    /**
     * Set mobile telephone number.
     *
     * @param string $telephoneMobile
     *
     * @return AddressBook
     */
    public function setTelephoneMobile($telephoneMobile)
    {
        $this->telephoneMobile = $telephoneMobile;

        return $this;
    }

    /**
     * Get mobile telephone number.
     *
     * @return string
     */
    public function getTelephoneMobile()
    {
        return $this->telephoneMobile;
    }

    /**
     * Returns address.
     *
     * @return array
     */
    public function getContactAddress()
    {
        $address = array();

        $address[] = ucwords(strtolower($this->getLine1()));

        if ($this->getLine2()) {
            $address[] = ucwords(strtolower($this->getLine2()));
        }

        $address[] = ucwords(strtolower($this->getCity()));
        $address[] = strtoupper(strtolower($this->getPostCode()));

        return $address;
    }

    /**
     * Set created
     *
     * @param datetime $created
     *
     * @return Invoice
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return datetime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param datetime $updated
     *
     * @return Invoice
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return datetime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set deleted
     *
     * @param datetime $deleted
     *
     * @return Invoice
     */
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;

        return $this;
    }

    /**
     * Get deleted
     *
     * @return datetime
     */
    public function getDeleted()
    {
        return $this->deleted;
    }
}

src/Xtreem/AddressBookBundle/Controller/AddressBookController.php
<?php

namespace Xtreem\AddressBookBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Doctrine\ORM\Query;
use Doctrine\ORM\Query\QueryException;

/**
 * AddressBook Controller.
 *
 * @category  Controller
 * @package   XtreemSimpleAddresBook
 * @author    Benjamin Ugbene <benjamin.ugbene@googlemail.com>
 * @copyright 2013 Benjamin Ugbene
 */
class AddressBookController extends Controller
{
    /**
     * Flash message success type.
     *
     * @var string
     */
    const TYPE_FLASH_MESSAGE_SUCCESS = 'success';

    /**
     * Flash message error type.
     *
     * @var string
     */
    const TYPE_FLASH_MESSAGE_ERROR = 'error';

    /**
     * Flash message warning type.
     *
     * @var string
     */
    const TYPE_FLASH_MESSAGE_WARNING = 'warning';

    /**
     * Flash message info type.
     *
     * @var string
     */
    const TYPE_FLASH_MESSAGE_INFO = 'info';

    /**
     * Service name.
     *
     * @var string
     */
    protected $serviceName = 'address_book_service';

    /**
     * Service.
     *
     * @var \Xtreem\AddressBookBundle\Service\AddressBookService
     */
    protected $service;

    /**
     * Current request.
     *
     * @var \Symfony\Component\HttpFoundation\Request
     */
    protected $request;

    /**
     * Session object.
     *
     * @var \Symfony\Component\HttpFoundation\Session\Session
     */
    protected $session;


    /**
     * Init action.
     *
     * @return void
     */
    protected function init()
    {
        $this->service = $this->get($this->serviceName);
        $this->request = $this->get('request');
        $this->session = $this->get('session');

        $this->service->setController($this);
        $this->service->init($this->container);
    }

    /**
     * Controller resolver action after container set.
     *
     * @return void
     */
    public function resolve()
    {
        $this->init();
    }

    /**
     * Index action.
     *
     * @Route("/", name="home")
     * @Template()
     *
     * @return array
     */
    public function indexAction()
    {
        $this->service->initDatatable();

        $token = $this->getCsrfToken();

        return array('_token' => $token);
    }

    /**
     * Show action.
     *
     * @Route("/{id}/show", requirements={"id" = "\d+"}, name="show")
     * @Template()
     *
     * @return array
     */
    public function showAction($id)
    {
        return array('entity' => $this->service->find($id));
    }

    /**
     * Add action.
     *
     * @Route("/add", name="add")
     * @Template()
     *
     * @return array
     */
    public function addAction()
    {
        $form = $this->service->getForm();
        if ($this->isPost()) {
            $result = $this->service->create($this->request);
            if ($result['result']) {
                $this->setFlashMessage(
                    self::TYPE_FLASH_MESSAGE_SUCCESS,
                    'Address book record was successfully added!'
                );

                return $this->redirect(
                    $this->generateUrl('show', array('id' => $result['id']))
                );
            }

            $form = $result['form'];
        }

        return array(
            'form'   => $form->createView(),
            'errors' => $form->getErrors(),
        );
    }

    /**
     * Edit action.
     *
     * @param integer $id Entry id.
     *
     * @Route("/{id}/edit", requirements={"id" = "\d+"}, name="edit")
     * @Template()
     *
     * @return array
     */
    public function editAction($id)
    {
        $form = $this->service->getForm($id);

        if ($this->isPost()){
            $result = $this->service->update($id, $this->request);
            if ($result['result']) {
                $this->setFlashMessage(
                    self::TYPE_FLASH_MESSAGE_SUCCESS,
                    'Address book record was successfully updated!'
                );

                return $this->redirect(
                    $this->generateUrl('show', array('id' => $result['id']))
                );
            }

            $form = $result['form'];
        }

        return array(
            'entity'   => $this->service->find($id),
            'editForm' => $form->createView(),
            'errors'   => $form->getErrors()
        );
    }

    /**
     * Delete action.
     *
     * @param integer $id Entry id.
     *
     * @Route(
     *     "/{id}/delete",
     *     requirements={"id" = "\d+", "_format" = "json"},
     *     name="delete"
     * )
     * @Template()
     *
     * @return array
     */
    public function deleteAction($id)
    {
        if (! $this->request->isXmlHttpRequest()) {
            throw new HttpException(400, 'Bad request.');
        }

        if (! $this->isCsrfTokenValid($this->request->request->get('_token'))) {
            throw new HttpException(500, 'Invalid CSRF token.');
        }

        try {
            $this->service->delete($id, $this->request);
            $response = array(
                'result'  => true,
                'message' => 'Address book record was deleted successfully.'
            );
        } catch (QueryException $e) {
            $response = array(
                'result'  => false,
                'message' => 'An error occured while attempting to delete address book record ',
            );
        }

        return new JsonResponse($response);
    }

    /**
     * Datatable grid action.
     *
     * @Route(
     *     "/grid",
     *     requirements={"_format" = "json"},
     *     name="grid"
     * )
     *
     * @return Response
     */
    public function gridAction()
    {
        return $this->service->initDatatable()->execute(Query::HYDRATE_OBJECT);
    }

    /**
     * Is it Post.
     *
     * @return boolean
     */
    protected function isPost()
    {
        return $this->getRequest()->getMethod() == 'POST';
    }

    /**
     * Sets flash messages.
     *
     * @param string $type    Type of flash message.
     * @param string $message Message to be displayed.
     *
     * @return void
     */
    protected function setFlashMessage($type, $message)
    {
        $this->session->getFlashBag()->add($type, $message);
    }

    /**
     * Returns a CSRF token.
     *
     * @return void
     */
    protected function getCsrfToken()
    {
        $csrfProvider = $this->get('form.csrf_provider');

        $token = $csrfProvider->generateCsrfToken(
            $this->container->getParameter('intention')
        );

        return $token;
    }

    /**
     * Validates CSRF token.
     *
     * @param string $token Token to validate.
     *
     * @return void
     */
    protected function isCsrfTokenValid($token)
    {
        $csrfProvider = $this->get('form.csrf_provider');

        return $csrfProvider->isCsrfTokenValid(
            $this->container->getParameter('intention'),
            $token
        );
    }
}

src/Xtreem/AddressBookBundle/Resources/views/AddressBook/add.html.twig
{% extends '::base.html.twig' %}

{% form_theme form 'XtreemAddressBookBundle:partials:form.theme.html.twig' %}

{% block title %}Add a new addressbook record{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{{ path('home') }}">Address book</a> <span class="divider">/</span></li>
        <li class="active">Add</li>
    </ul>

    <div class="page-header">
        <h2> Add address book record </h2>
    </div>

    {%
        include 'XtreemAddressBookBundle:partials:form.html.twig' with {
            'form':       form,
            'formAction': path('add'),
            'cancelUrl':  path('home')
        }
    %}
{% endblock %}

src/Xtreem/AddressBookBundle/Resources/views/AddressBook/edit.html.twig
{% extends '::base.html.twig' %}

{% form_theme editForm 'XtreemAddressBookBundle:partials:form.theme.html.twig' %}

{% block title %}Edit a new addressbook record{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{{ path('home') }}">Address book</a> <span class="divider">/</span></li>
        <li class="active">Edit</li>
    </ul>

    <div class="page-header">
        <h2> Edit address book record </h2>
    </div>

    {%
        include 'XtreemAddressBookBundle:partials:form.html.twig' with {
            'form':       editForm,
            'formAction': path('edit', { 'id' : entity.id }),
            'cancelUrl':  'javascript:history.go(-1)'
        }
    %}
    </form>
{% endblock %}

src/Xtreem/AddressBookBundle/Resources/views/AddressBook/index.html.twig
{% extends '::base.html.twig' %}
{% block body %}
    <div class="hero-unit">
        <h1>Simple Address Book</h1>
        <p>This is my simple Symfony2 address book bundle. Enjoy!!</p>
    </div>

    {{
        datatable({
            'id':            'addressbook',
            'view_route':    'show',
            'edit_route':    'edit',
            'delete_route':  'delete',
            'delete_token':  _token,
            'main_template': 'XtreemAddressBookBundle:partials:datatable_template.html.twig',
            'js' : {
                'sAjaxSource' : path('grid')
            }
        })
    }}

    <div class="form-actions">
        <a class="btn btn-primary" href="{{ path('add') }}">
            Add new address book record
        </a>
    </div>
{% endblock %}

src/Xtreem/AddressBookBundle/Resources/views/AddressBook/show.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{{ path('home') }}">Address book records</a> <span class="divider">/</span></li>
        <li><a href="{{ path('show', { 'id': entity.id }) }}"> {{entity.id}} </a> <span class="divider">/</span></li>
        <li class="active">Show</li>
    </ul>
    <div class="page-header">
        <h1>Address book record</h1>
    </div>
    <div class="row" style="margin-top: 10px;">
        <div id="contact-details" class="span6">
            <h3> Details </h3>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <td>{{ entity.id }}</td>
                    </tr>
                    <tr>
                        <th>First name</th>
                        <td>{{ entity.firstName | title }}</td>
                    </tr>
                    <tr>
                        <th>Last name</th>
                        <td>{{ entity.lastName | title }}</td>
                    </tr>
                    <tr>
                        <th>Telephone home</th>
                        <td>{{ entity.telephoneHome }}</td>
                    </tr>
                    <tr>
                        <th>Telephone mobile</th>
                        <td>{{ entity.telephoneMobile }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="contact-client-details" class="span6">
            <h3>Contact address</h3>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td>
                            <address>
                                {% for line in entity.contactAddress %}
                                    {{ line }}<br/>
                                {% endfor %}
                            </address>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-actions">
        <a class="btn" href="{{ path('home') }}">
            Back to list of addresses
        </a>
        <a class="btn btn-primary" href="{{ path('edit', { 'id': entity.id }) }}">Edit</a>
    </div>
{% endblock %}